apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-anchoreengine-dev-01
  namespace: anchoreengine-dev-01
spec:
  storageClassName: pv-anchoreengine-dev-01
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/anchoreengine/
